### ISSUE TITLE
setattr不成功导致无法成功设置msgtype

### ISSUE THREAD

**Issue by yafeiaa** [WuJunkai2004/Dingbot#2]
```python
def __getattr__(self, mothed):
        self.__api__ = mothed
        return self.send
```
这段代码中，重写了getattr方法，还需要调用一下super，否在，在执行self.send的时候无法读取到self.__api__=mothed设置的api值

**Comment by WuJunkai2004** [comment]
很抱歉现在才看到您的issues
是否可以提供一下相应报错？
我这边测试的时候一切正常，send函数里面是可以读取到改变以后的\_\_api\_\_的值的

**Comment by yafeiaa** [comment]
这个有点久了，忘记之前怎么触发的了
